<?php

namespace App\Models;

use App\Models\Author;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;

    protected static function boot()
    {
        self::deleting(function (self $book) {
            $book->authors()->detach();
        });

        parent::boot(); // TODO: Change the autogenerated stub
    }

    protected $fillable = [
        'name'
    ];

    public function authors()
    {
        return $this->belongsToMany(Author::class, BookAuthor::class, 'book_id', 'author_id');
    }
}
